---
version: 1.0.0
bibliography: references.bib
csl: ../../assets/csl/apa.csl
author:
  - name: Samuel Szoniecky
    orcid: 0000-0002-7643-3342
    email: samuel.szoniecky@univ-paris8.fr
    affiliations:
      - name: Laboratoire Paragraphe
        address: Université Paris 8
        city: Saint-Denis
        country: France
---

Proposition pour l'appel à article : [Le 4ème paradigme en question](https://intelligibilite-numerique.numerev.com/appels-a-articles/2921-appel-a-articles-n-7-2025)

# Du texte au diagramme : analyser la symbiose entre acteurs, agents et environnement

La multiplication des grands modèles de langage (LLM) et leurs usages de plus en plus nombreux placent les technologies intelligentes [@verlaet2020] au cœur des pratiques scientifiques que ce soit pour gérer la production de textes, pour calculer des modèles économiques, biologiques ou physique ou même pour gagner un prix Nobel [@mauger2025]. L'IA devient un consommable au même titre que le traitement de texte qui a révolutionné l'éditorialisation scientifique il y a plus de trente ans [@biezunski1989], ou le CMS il y a plus de vingt ans [@broudoux2005]. Aujourd'hui, les outils numériques forment des environnements spécifiques, des milieux [@berque2009], dans lesquels nous évoluons en nous "co-développant" [@bachimont2020]. Humains et machines partagent des écosystèmes communs dont ils sont les acteurs humains [@callon2006] ou les agents numériques [@abrami2014; @balbo2018; @barkol2025]. Ils possèdent des compétences spécifiques et des manières d'être [@latour2012] qui ne sont pas toujours réciproquement profitables. D'autant moins quand on prend en compte ces environnements dans leurs dimensions géopolitiques [@saleh2024].

Pourquoi le développement de ces environnements est de plus en plus rapide et global alors qu'ils ne sont pas toujours durable et profitables ?

Comment évaluer dans les activités scientifiques la durabilité et la profitabilité réciproque, la symbiose, entre acteurs, agents et environnements ?

Dans cet article, nous souhaitons discuter la proposition du 4ème paradigme présentée par [@tansley2009] en montrant pourquoi l’exploration des données massives comme processus de découverte scientifique occupe désormais une place prépondérante dans l'activité scientifique et comment évaluer la durabilité et la profitabilité de ces pratiques.

Dans un premier temps, nous expliquerons pourquoi le travail scientifique tend vers un dépassement de la pensée textuelle au profit d'une pensée diagrammatique qui mobilise des "schémas interprétatifs" [@bachimont2020] impliquant des capacités de calcul de plus en plus grandes et une adéquation de plus en plus forte entre acteurs et agents.

Nous montrerons ensuite comment modéliser des actions situées [@quéré2020] et des protocoles [@sauret2017] liés à l'écriture d'un article scientifique, afin de mesurer pour les acteurs, les agents et l'environnement, l'augmentation et la diminution de leurs pouvoirs de discernement, de raisonnement et d'action [@szoniecky2020]. Nous analyserons ensuite ces mesures pour évaluer des niveaux de symbiose en comparant la réciprocité et la durabilité des fluctuations de puissances.

Avec cet article, nous souhaitons orienter la réflexion sur l'intelligibilité du numérique vers une prise en compte de l'adéquation durable, profitable et réciproque entre acteurs, agents et environnement. Ce qui nous intéresse ici, c'est de poser les bases d'une discussion sur l'éthique du numérique comprise comme la décision d'exercer ou non les pouvoirs que nous octroient les machines.